(() => {
'use strict';
const $=id=>document.getElementById(id), PAYLOAD='payload.txt', URL_FILE='url.txt', PAYLOAD_SIZE=128684,
FALLBACK=16384, OVERHEAD=4096, MAX_URLS=100, MAX_EXT=262144, MAX_ROUTE=5120, ROUTE_TIMEOUT=5000, HISTORY='ggHistoryV2',
AMOUNTS={'0.01':['£0.01',42895],'0.02':['£0.02',85790],'0.03':['£0.03',128684]};
const amount=$('amountSelect'),start=$('consumeButton'),check=$('checkButton'),clear=$('clearButton'),input=$('urlInput'),
urlSummary=$('urlSummary'),routeSummary=$('routeSummary'),routeResults=$('routeResults'),budgetTitle=$('budgetTitle'),
budgetSummary=$('budgetSummary'),budgetDetail=$('budgetDetail'),status=$('status'),historyList=$('historyList');
let pageBytes=0,cutoff=performance.now(),busy=false,checking=false,loading=true,measurePromise;
const rnd=()=>crypto?.getRandomValues?crypto.getRandomValues(new Uint32Array(1))[0]/4294967296:Math.random();
const ri=(a,b)=>Math.floor(rnd()*(b-a+1))+a;
const shuffle=a=>{a=a.slice();for(let i=a.length-1;i;i--){const j=ri(0,i);[a[i],a[j]]=[a[j],a[i]]}return a};
const fmt=n=>!Number.isFinite(n)?'—':n<1024?`${Math.round(n)} B`:n<1048576?`${(n/1024).toFixed(2)} KB`:`${(n/1048576).toFixed(2)} MB`;
const readStore=(k,d)=>{try{const v=localStorage.getItem(k);return v===null?d:v}catch{return d}};
const writeStore=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
const sameOrigin=u=>{try{return new URL(u,location.href).origin===location.origin}catch{return false}};
const metric=e=>Number(e?.transferSize)||Number(e?.encodedBodySize)||0;
function preview(){const [label,base]=AMOUNTS[amount.value]||AMOUNTS['0.01'],min=Math.round(base*.8),max=Math.round(base*1.2),reserve=(pageBytes||FALLBACK)+OVERHEAD;
budgetTitle.textContent=`本次目标：${label}（实际会随机 ±20%）`;
budgetSummary.textContent=`总目标约 ${fmt(min)}–${fmt(max)}；页面初始流量已计入：${fmt(pageBytes||FALLBACK)}`;
budgetDetail.textContent=`URL 与自有填充可使用约 ${fmt(Math.max(0,min-reserve))}–${fmt(Math.max(0,max-reserve))}（另预留 ${fmt(OVERHEAD)} 协议开销）`}
function measure(){if(pageBytes)return;let n=metric(performance.getEntriesByType('navigation')[0]);for(const e of performance.getEntriesByType('resource'))if(e.startTime<=cutoff&&sameOrigin(e.name))n+=metric(e);
if(!n)n=Math.max(FALLBACK,Math.min(new TextEncoder().encode(document.documentElement.outerHTML).byteLength,32768));pageBytes=Math.round(n);preview()}
function waitMeasure(){if(pageBytes)return Promise.resolve();if(!measurePromise)measurePromise=new Promise(r=>{const f=()=>{cutoff=performance.now();measure();r()};document.readyState==='complete'?f():addEventListener('load',f,{once:true})});return measurePromise}
function parseLine(line){let s=line.trim();if(!s)return null;const legacy=/\s*\|\s*(\d+)\s*$/.exec(s);let old=false;if(legacy){const n=+legacy[1];if(!Number.isInteger(n)||n<1||n>MAX_EXT)throw Error('预计字节数必须在 1–262144 之间');s=s.slice(0,legacy.index).trim();old=true}
const u=new URL(s);if(!['http:','https:'].includes(u.protocol))throw Error('只允许 HTTP/HTTPS URL');if(location.protocol==='https:'&&u.protocol!=='https:')throw Error('HTTPS 页面不能读取 HTTP 资源');if(u.username||u.password)throw Error('不允许包含账号或密码的 URL');u.hash='';return{url:u.href,old}}
function parse(){const records=[],invalid=[],seen=new Set();input.value.split(/\r?\n/).forEach((line,i)=>{if(!line.trim())return;if(records.length>=MAX_URLS){invalid.push([i+1,`超过最多 ${MAX_URLS} 条`]);return}try{const r=parseLine(line);if(!seen.has(r.url)){seen.add(r.url);records.push(r)}}catch(e){invalid.push([i+1,e.message||'URL 无效'])}});return{records,invalid}}
function updateSummary(){const p=parse();if(!p.records.length){urlSummary.textContent='当前为空：点击开始时将全部使用页面自身填充文件。';return}const old=p.records.filter(x=>x.old).length;urlSummary.textContent=`已识别 ${p.records.length} 个 URL${old?`，其中 ${old} 个含旧版预计字节写法`:''}${p.invalid.length?`；忽略 ${p.invalid.length} 行`:''}`}
async function loadUrls(){start.disabled=check.disabled=clear.disabled=true;routeSummary.textContent='正在从 url.txt 加载默认线路…';const u=new URL(URL_FILE,location.href);u.searchParams.set('_ts',Date.now());try{const r=await fetch(u,{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw Error(`HTTP ${r.status}`);input.value=(await r.text()).trim();routeSummary.textContent=input.value?'已从 url.txt 加载默认线路；当前修改仅在本页面临时有效。':'url.txt 当前为空；运行时将使用页面自身填充文件。'}catch(e){input.value='';routeSummary.textContent=`默认线路加载失败（${e.message||'未知错误'}），可手动输入；留空将使用页面自身填充文件。`}finally{cutoff=performance.now();updateSummary();await waitMeasure();loading=false;start.disabled=check.disabled=clear.disabled=false}}
const timeout=ms=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);return[c,()=>clearTimeout(t)]};
async function readBytes(r,limit){if(r.type==='opaque')throw Error('CORS 不允许读取响应');if(!r.body?.getReader){const b=await r.blob();return{bytes:Math.min(b.size,limit),truncated:b.size>limit}}const rd=r.body.getReader();let bytes=0,truncated=false;try{for(;;){const p=await rd.read();if(p.done)break;if(bytes+p.value.byteLength>limit){bytes=limit;truncated=true;await rd.cancel();break}bytes+=p.value.byteLength}}finally{rd.releaseLock()}return{bytes,truncated}}
async function external(r,cap){const[c,done]=timeout(10000),t=performance.now();try{const x=await fetch(r.url,{mode:'cors',credentials:'omit',cache:'no-store',redirect:'follow',signal:c.signal});if(x.type==='opaque')throw Error('CORS 不允许读取响应');if(!x.ok)throw Error(`HTTP ${x.status}`);const b=await readBytes(x,Math.min(cap,MAX_EXT));return{ok:true,bytes:b.bytes,duration:performance.now()-t,finalUrl:x.url,type:x.headers.get('content-type')||''}}finally{done()}}
async function filler(needed,id){let left=Math.max(0,Math.floor(needed)),offset=0,total=0,count=0;while(left>0&&count<12){const a=offset%PAYLOAD_SIZE,size=Math.min(left,PAYLOAD_SIZE-a),b=a+size-1,u=new URL(PAYLOAD,location.href);u.searchParams.set('part',count);u.searchParams.set('_gg',`${id}-${Math.floor(rnd()*1e9)}`);const r=await fetch(u,{cache:'no-store',headers:{Range:`bytes=${a}-${b}`}});if(!r.ok&&r.status!==206)throw Error(`自有填充文件请求失败（HTTP ${r.status}）`);const x=await readBytes(r,size);if(!x.bytes)throw Error('自有填充文件返回为空');total+=x.bytes;left-=x.bytes;offset=(a+x.bytes)%PAYLOAD_SIZE;count++}if(left>0)throw Error('自有填充文件未能达到目标字节数');return{bytes:total,count}}
function renderHistory(){historyList.textContent='';let a=[];try{a=JSON.parse(readStore(HISTORY,'[]'));if(!Array.isArray(a))a=[]}catch{}if(!a.length){const d=document.createElement('div');d.className='history-item';d.textContent='暂无记录';historyList.append(d);return}for(const x of a.slice(-5).reverse()){const d=document.createElement('div');d.className='history-item';d.textContent=`✓ ${x.date} · ${x.amount} · 总计约 ${fmt(x.totalBytes)}${x.urlCount?`，URL ${x.urlCount} 个`:'，纯自有填充'}`;historyList.append(d)}}
function saveHistory(x){let a=[];try{a=JSON.parse(readStore(HISTORY,'[]'));if(!Array.isArray(a))a=[]}catch{}a.push(x);writeStore(HISTORY,JSON.stringify(a.slice(-20)));renderHistory()}
function renderRoutes(a){routeResults.textContent='';for(const x of a){const d=document.createElement('div');d.className='route-row';const s=document.createElement('span');s.className=`route-state ${x.keep?'route-ok':'route-fail'}`;s.textContent=x.keep?'保留':'移除';const q=document.createElement('span');q.className='route-detail';q.textContent=`${x.url} · HTTP ${x.status??'—'} · CORS：${x.cors===true?'是':x.cors===false?'否':'未知'} · 正文：${x.size??'—'}${x.reason?` · ${x.reason}`:''}`;d.append(s,q);routeResults.append(d)}}
async function probe(r){const[c,done]=timeout(ROUTE_TIMEOUT);let res;try{res=await fetch(r.url,{mode:'cors',credentials:'omit',cache:'no-store',redirect:'follow',signal:c.signal});const cors=res.type==='cors'||res.type==='basic'||sameOrigin(res.url),base={url:r.url,status:res.status,cors};if(!cors||res.type==='opaque')return{...base,reason:'CORS 未通过'};if(!res.ok)return{...base,reason:'HTTP 状态不是 2xx'};if(new URL(res.url).protocol!=='https:')return{...base,reason:'最终地址不是 HTTPS'};const len=Number(res.headers.get('content-length'));if(Number.isFinite(len)&&len>MAX_ROUTE)return{...base,size:`${fmt(len)}（超过 5120 B）`,reason:'正文过大'};const b=await readBytes(res,MAX_ROUTE);if(b.truncated)return{...base,size:`>${MAX_ROUTE} B`,reason:'正文过大'};if(!b.bytes)return{...base,size:'0 B',reason:'正文为空'};return{...base,keep:true,size:fmt(b.bytes)}}catch(e){return{url:r.url,status:res?.status??null,cors:res?false:null,reason:e.name==='AbortError'?`请求超过 ${ROUTE_TIMEOUT/1000} 秒`:(e.message||'请求失败')}}finally{done()}}
async function checkRoutes(){if(busy||checking||loading)return;const p=parse();if(!p.records.length){input.value='';updateSummary();routeSummary.textContent='当前没有可检测的有效 URL；运行时将使用页面自身填充。';return}checking=true;start.disabled=check.disabled=clear.disabled=true;const out=p.invalid.map(x=>({url:`第 ${x[0]} 行`,reason:x[1]}));renderRoutes(out);try{for(let i=0;i<p.records.length;i++){routeSummary.textContent=`正在检测 ${i+1}/${p.records.length}（单条最多 ${ROUTE_TIMEOUT/1000} 秒）：${p.records[i].url}`;out.push(await probe(p.records[i]));renderRoutes(out)}const kept=out.filter(x=>x.keep).map(x=>x.url);input.value=kept.join('\n');updateSummary();routeSummary.textContent=`检测完成：共 ${out.length} 条，保留 ${kept.length} 条，移除 ${out.length-kept.length} 条；结果仅在当前页面有效。`}finally{checking=false;start.disabled=check.disabled=clear.disabled=false}}
function show(kind,title,detail){status.className=kind;status.textContent='';const a=document.createElement('div');a.textContent=title;status.append(a);if(detail){const b=document.createElement('div');b.className='stats';b.textContent=detail;status.append(b)}}
async function consume(){if(busy||checking||loading)return;busy=true;start.disabled=check.disabled=clear.disabled=true;const t=performance.now();await waitMeasure();const p=parse(),[label,base]=AMOUNTS[amount.value]||AMOUNTS['0.01'],target=Math.round(base*(.8+rnd()*.4)),budget=Math.max(1024,target-((pageBytes||FALLBACK)+OVERHEAD)),id=`${Date.now().toString(36)}-${Math.floor(rnd()*1e9).toString(36)}`,chosen=shuffle(p.records).slice(0,p.records.length>=3?ri(3,Math.min(5,p.records.length)):p.records.length);show('loading','📡 正在执行本次测试…',`目标总量 ${fmt(target)}；已扣除页面初始流量 ${fmt(pageBytes||FALLBACK)}`);try{let ext=0,failed=0;for(let i=0;i<chosen.length;i++){const cap=Math.max(1,Math.floor((budget-ext)/(chosen.length-i)));try{const r=await external(chosen[i],cap);ext+=r.bytes}catch{failed++}show('loading',`🌐 正在访问自定义 URL（${i+1}/${chosen.length}）…`,`已读取 ${fmt(ext)}`)}const remain=Math.max(0,budget-ext);let fill={bytes:0,count:0};if(remain){show('loading','📦 正在用自有填充文件补齐…',`还需约 ${fmt(remain)}`);fill=await filler(remain,id)}const content=ext+fill.bytes,total=(pageBytes||FALLBACK)+OVERHEAD+content;show('success','✅ 本次测试完成',`目标 ${fmt(target)} · 页面 ${fmt(pageBytes||FALLBACK)} · 内容 ${fmt(content)} · URL ${chosen.length} 个${failed?`；${failed} 个不可读取，已补足`:''} · ${((performance.now()-t)/1000).toFixed(2)} 秒`);saveHistory({date:new Date().toLocaleString('zh-CN',{hour12:false}),amount:label,totalBytes:total,urlCount:chosen.length,timestamp:Date.now()});start.textContent='🔄 再次测试'}catch(e){show('error','❌ 操作失败',e.message||'网络请求失败，请稍后重试')}finally{busy=false;start.disabled=check.disabled=clear.disabled=false}}
amount.addEventListener('change',preview);start.addEventListener('click',consume);check.addEventListener('click',checkRoutes);clear.addEventListener('click',()=>{input.value='';updateSummary();routeSummary.textContent='当前列表已临时清空；刷新后会重新读取 url.txt。';routeResults.textContent=''});input.addEventListener('input',updateSummary);
preview();renderHistory();updateSummary();loadUrls();
})();